# Generated by Django 4.1.5 on 2023-04-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus_content", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArticlePost",
        ),
    ]
