# Generated by Django 4.1.5 on 2023-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus_content", "0002_delete_articlepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(default="aaa", max_length=255),
            preserve_default=False,
        ),
    ]
