# Generated by Django 4.1.5 on 2023-01-08 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('img', models.FileField(max_length=255, upload_to='academic/meeting/')),
                ('abstract', models.TextField(max_length=255)),
                ('text', models.TextField(max_length=32367)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
