# Generated by Django 4.1.3 on 2022-11-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
    ]
